### PR TITLE
Feature/issue 37 route net gateway support

### PR DESCRIPTION
**Pull request by LePhanFF**

### CODE REVIEW

**Comment by LePhanFF** [comment]
`ubuntu@ip-10-1-8-103:~/terraform-provider-pritunl$ sudo make test
tf_pritunl_acc_test
e87685df512dc91f1c3916835deb4c563a36d0cd394d7ea4f26e77e20f63b6df
sleep 40
./tools/wait-for-it.sh localhost:27017 -- echo "mongodb is up"
wait-for-it.sh: waiting 15 seconds for localhost:27017
wait-for-it.sh: localhost:27017 is available after 0 seconds
mongodb is up
# enables an api access for the pritunl user, updates an api token and secret
MongoDB shell version v4.4.15
connecting to: mongodb://127.0.0.1:27017/pritunl?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("74599192-c325-49ae-bfd5-cc22e4ac0730") }
MongoDB server version: 4.4.15
{ "acknowledged" : true, "matchedCount" : 1, "modifiedCount" : 1 }
bye
TF_ACC=1 \
PRITUNL_URL="https://localhost/" \
PRITUNL_INSECURE="true" \
PRITUNL_TOKEN=tfacctest_token \
PRITUNL_SECRET=tfacctest_secret \
go test -v -cover -count 1 ./internal/provider
=== RUN   TestDataSourceHost
=== PAUSE TestDataSourceHost
=== RUN   TestAccOrganization_basic
=== PAUSE TestAccOrganization_basic
=== RUN   TestGetServer_basic
--- PASS: TestGetServer_basic (5.09s)
=== RUN   TestGetServer_with_attached_organization
--- PASS: TestGetServer_with_attached_organization (4.17s)
=== RUN   TestGetServer_with_a_few_attached_organizations
--- PASS: TestGetServer_with_a_few_attached_organizations (7.61s)
=== RUN   TestGetServer_with_attached_route
--- PASS: TestGetServer_with_attached_route (6.18s)
=== RUN   TestGetServer_with_a_few_attached_routes
--- PASS: TestGetServer_with_a_few_attached_routes (5.44s)
=== RUN   TestGetServer_with_invalid_route
--- PASS: TestGetServer_with_invalid_route (1.46s)
=== RUN   TestCreateServer_with_invalid_network
--- PASS: TestCreateServer_with_invalid_network (1.50s)
=== RUN   TestCreateServer_with_unsupported_network
--- PASS: TestCreateServer_with_unsupported_network (3.90s)
=== RUN   TestCreateServer_with_invalid_bind_address
--- PASS: TestCreateServer_with_invalid_bind_address (3.99s)
=== RUN   TestGetServer_with_default_host
--- PASS: TestGetServer_with_default_host (3.32s)
=== RUN   TestGetServer_without_hosts
--- PASS: TestGetServer_without_hosts (4.91s)
=== RUN   TestAccUser_basic
=== PAUSE TestAccUser_basic
=== CONT  TestDataSourceHost
=== CONT  TestAccUser_basic
=== CONT  TestAccOrganization_basic
--- PASS: TestDataSourceHost (4.11s)
--- PASS: TestAccOrganization_basic (8.24s)
--- PASS: TestAccUser_basic (12.60s)
PASS
coverage: 62.8% of statements
ok      github.com/disc/terraform-provider-pritunl/internal/provider    60.208s coverage: 62.8% of statements
tf_pritunl_acc_test


`

The test passed 

and the attribute net_gateway was created

image

**Review by disc — APPROVED** [review]

**Comment by disc** [comment]
Hey @LePhanFF, thanks for your contribution!

**Comment by disc** [comment]
@LePhanFF I can't merge your MR without green tests, but i see 0 checks after you change the branch. Can you try to create a new pull request with "green" tests?

**Review by disc — CHANGES_REQUESTED** [review]
Tests workflow should be passed successfully, no "checks" were executed in this PR

**Comment by LePhanFF** [comment]
Hello @disc 
It appears that the green checks are awaiting for your approval to run since I am merging from a forked repository.  My green tests have passed at in my own repo at

https://github.com/LePhanFF/terraform-provider-pritunl/pull/4
https://github.com/LePhanFF/terraform-provider-pritunl/actions/runs/5985348475

I believe if you approve the workflow it should be good to go.  If not, you might have to add me to be a repo contributor for me to create a branch with my changes.

Thanks, 

Le

**Review by disc — APPROVED** [review]

**Comment by LePhanFF** [comment]
@disc Thank you so much.  Let me know when you can release the next version for this, any estimated ETA would be great, I have a bug in pritunl server eagerly trying to fix with setting up net gateway route.

**Comment by disc** [comment]
@LePhanFF new version has been released

**Pull request merged**
